#!/bin/ksh
#
trap "" 2
d_MenuInic=/dwh/producao/geral/menu
a_apoio1=/home/sql_apoio/menu1.${$}
blk=$(tput blink)
bol=$(tput bold)
nul=$(tput sgr0)
rev=$(tput rev)
apg=$(tput dim)
integer v_Line=0
integer v_Opcao
integer v_Ret=1
integer v_Nivel=1
integer v_Erro=0
d_Menu[$v_Nivel]=$d_MenuInic
function fn_Repeat
{
v_Repeat=""
integer v_i=1
integer v_r=$1
while (( $v_i <= $v_r ))
do
        v_Repeat="${v_Repeat}${2}"
        v_i=$v_i+1
done
echo "$v_Repeat\c"
return
}
function fn_Mensagem
{
v_Mensagem=$1
integer v_NString=${#v_Mensagem} 
integer v_i=1
integer v_Borda=78-$v_NString
v_Borda=$v_Borda/2
echo ""
fn_Repeat $v_Borda " ";echo "+\c";fn_Repeat $v_NString -;echo "+"
fn_Repeat $v_Borda " ";echo "+\c";echo "${bol}$v_Mensagem${nul}\c";echo "+"
fn_Repeat $v_Borda " ";echo "+\c";fn_Repeat $v_NString -;echo "+"
sleep 3
}
function fn_fim_menu
{
rm -f $a_apoio1
}
function fn_TelaPrin
{
clear
print "+\c";fn_Repeat 78 -;print "+"
print "|        S I S T E M A   D E   C O N T R O L E   D E   E X E C U C A O         |"
print "|   $(date +%d/%m/%Y)         $(tput blink)   Administracao Carga DATA WAREHOUSE $(tput sgr0)           $(date +%H:%M)  |"
print "+\c";fn_Repeat 78 -;print "+"
echo; echo
}
function fn_CarregaMenu
{
v_Line=0
ls ${d_Menu[$v_Nivel]} > ${a_apoio1}
fn_TelaPrin
while read line
do
v_Line=v_Line+1
	if [ -d ${d_Menu[$v_Nivel]}/${line} ]
	then
  	   if  [ $( find ${d_Menu[$v_Nivel]}/${line}/ -name *.menu 2>/dev/null | wc -l ) = 0 ]
	   then
		  print "                    \n\t\t                    ${bol} $v_Line ${apg} - ${line}${nul}"
	   else
		  print "                    \n\t\t                    ${bol} $v_Line ${nul} - ${line}"
	   fi
	else
	   print "                    \n\t\t                    ${bol} $v_Line ${nul} - ${line%%.menu}" 
	fi
done < ${a_apoio1}
print "                    \n\t\t                    ${bol} . ${nul} - FIM"
print "\n\t          Escolha o comando a executar e tecle" $(tput bold) "ENTER:" $(tput sgr0) "\c"
}

while [ $v_Ret = 1 ]
do
	fn_CarregaMenu
	read v_Opcao 
        if [ $? -ne 0 ] || (( $v_Opcao < 0 )) || (( $v_Opcao > $(wc -l ${a_apoio1} | tr -s ' ' ':' | cut -f2 -d':' ) ))
	then
		v_Erro=$v_Erro+1
		if (( $v_Erro > 3 ))
		then
			if (( $v_Nivel == 1 ))
	                then
	                        break
	                else
	                        d_Menu[$v_Nivel]=""
	                        v_Nivel=v_Nivel-1
				continue
       		         fi
		fi
		fn_Mensagem "Entre com um número válido, tentativa [$v_Erro de 3]"
		continue
	else
		v_Erro=0
	fi
	if (( $v_Opcao == 0 ))
	then
		if (( $v_Nivel == 1 ))
		then
			break
		else
			d_Menu[$v_Nivel]=""		
			v_Nivel=v_Nivel-1
			continue
		fi
	else 
		v_Objeto=${d_Menu[$v_Nivel]}/`head -$v_Opcao ${a_apoio1} | tail -1`
		if [ -d $v_Objeto ]
		then
			if  [ $( find $v_Objeto -name *.menu 2>/dev/null | wc -l ) = 0 ]
			then
				fn_Mensagem "Esta opcao esta em construcao!!!"
				continue
			fi
			v_Nivel=v_Nivel+1
			d_Menu[$v_Nivel]=/$v_Objeto
		        	
		else
			if [ -f $v_Objeto ] 
			then
				. $v_Objeto
			else
				fn_Mensagem "Objeto nao e valido"
			fi
		fi
	fi
done
fn_fim_menu
exit;
